// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BlastTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createablastwithmessage() {
    driver.get("https://staging.cicle.app/blasts/6110ed43ca2953b5d4314a7f");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("textarea:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#fontSize-1 > .fr-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("textarea:nth-child(1)")).sendKeys("message");
    driver.findElement(By.cssSelector(".fr-element")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>message</p>'}", element);
    }
    driver.findElement(By.cssSelector(".Paper_Paper__27gPv")).click();
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".col-1:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".Post_Post__1nxel:nth-child(1) .Post_contentSection__33WUN > div > p")).getText(), is("Danu Ardhian - message"));
  }
  @Test
  public void createablastwithouttitle() {
    driver.get("https://staging.cicle.app/blasts/6110ed43ca2953b5d4314a7f");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#formatOLSimple-1 > .fr-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.id("notistack-snackbar")).getText(), is("Field parameter not complete."));
  }
  @Test
  public void createablast() {
    driver.get("https://staging.cicle.app/blasts/6110ed43ca2953b5d4314a7f");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.id("moreParagraph-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("textarea:nth-child(1)")).click();
    driver.findElement(By.cssSelector("textarea:nth-child(1)")).sendKeys("blast");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    js.executeScript("window.scrollTo(0,0)");
    assertThat(driver.findElement(By.id("notistack-snackbar")).getText(), is("Create post successful"));
  }
  @Test
  public void addasubscriber() {
    driver.get("https://staging.cicle.app/blasts/6110ed43ca2953b5d4314a7f");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.id("formatULOptions-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".CreateBlastPage_plusButton__26Vtt > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(2) > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(3) > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(4) > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__checkIcon__3x3Fw")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__Header__1jlWK > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".CreateBlastPage_plusButton__26Vtt > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(2) > .mr-auto")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(3) > .mr-auto")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(4) > .mr-auto")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(5) > .mr-auto")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__Header__1jlWK path")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("div:nth-child(1) > span"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void removeasubscriber() {
    driver.get("https://staging.cicle.app/blasts/6110ed43ca2953b5d4314a7f");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".CreateBlastPage_plusButton__26Vtt > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(3) path")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__teamMember__dAJ8o:nth-child(4) path")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__checkIcon__3x3Fw > path")).click();
    driver.findElement(By.cssSelector(".ManageSubscribersContainer_ManageSubscribersContainer__Header__1jlWK > .MuiSvgIcon-root")).click();
    assertThat(driver.findElement(By.cssSelector("strong")).getText(), is("This blast post doesn\\\'t have any members. Please add one."));
  }
}
