// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BoardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addnewcardwithoutname() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    assertThat(driver.findElement(By.id("notistack-snackbar")).getText(), is("Card name cannot be empty"));
  }
  @Test
  public void addnewlist() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 1040));
    driver.findElement(By.linkText("Add List")).click();
    driver.findElement(By.name("name")).sendKeys("test4");
    driver.findElement(By.cssSelector(".Button_container__1WNuB")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".List_List__30q9z:nth-child(4) h1"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void addnewlistwithoutname() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.linkText("Add List")).click();
    driver.findElement(By.cssSelector(".Button_container__1WNuB")).click();
    assertThat(driver.findElement(By.id("notistack-snackbar")).getText(), is("List name cannot be empty"));
  }
  @Test
  public void opencarddetails() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.cssSelector("#listcard_content-0 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    assertThat(driver.findElement(By.cssSelector(".ManageAttachments_mediumTitle__8RnWX")).getText(), is("Attachments"));
  }
  @Test
  public void addacomment() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.linkText("Add Card")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("Comment");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector("#listcard_content-0 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".CreateCommentForm_formInitial__3AVVg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#italic-1 > .fr-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>comment</p>'}", element);
    }
    driver.findElement(By.cssSelector("div:nth-child(1) > .btn-success > .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(1) > .btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.findElement(By.cssSelector(".fr-view > p")).getText(), is("comment"));
  }
  @Test
  public void addamember() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.findElement(By.linkText("Add Card")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("member");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#listcard_content-0 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#listcard_content-0 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".CardDetailContainer_CardDetailContainer__smallSectionContainer__3qfM5:nth-child(1) > .CardDetailContainer_buttonAction__2Sfwo:nth-child(2) .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".CardDetailContainer_CardDetailContainer__smallSectionContainer__3qfM5:nth-child(1) > .CardDetailContainer_buttonAction__2Sfwo:nth-child(2) .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("(//img[contains(@src,\'https://lh3.googleusercontent.com/a-/AOh14GheqRyQPp-zp7YCPLKjii5T8mu7n99AAuzhr2eOSA=s96-c\')])[4]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".OverlayButton_container__3kxDV:nth-child(3) .mr-auto")).click();
  }
  @Test
  public void addnewcard() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("bug5");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void addnewnote() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(978, 680));
    driver.findElement(By.linkText("Add Card")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("note1");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector("#listcard_content-0 > .OverlayButton_container__3kxDV:nth-child(2) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".ManageDesc_sectionEmptyDesc__md0ll")).click();
    {
      WebElement element = driver.findElement(By.id("strikeThrough-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>note</p>'}", element);
    }
    driver.findElement(By.cssSelector("div:nth-child(1) > .btn-success")).click();
    assertThat(driver.findElement(By.cssSelector(".fr-view > p")).getText(), is("note"));
  }
  @Test
  public void addduedate() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".form-control")).sendKeys("bug7");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".CardDetailContainer_buttonAction__2Sfwo:nth-child(4) > .btn > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector(".ManageDueDateContainer_datePicker__1LCTx .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".MuiPickersCalendar-week:nth-child(4) > div:nth-child(3) .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-textPrimary:nth-child(2) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".ManageDueDateContainer_timePicker__3MoTG .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".MuiPickersClock-squareMask")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-textPrimary:nth-child(2) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-textPrimary:nth-child(2) > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".DateBox_DateBox__3UL8M:nth-child(2) > p:nth-child(2)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void archiveacard() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".form-control")).sendKeys("bug9");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".CardDetailContainer_buttonAction__2Sfwo:nth-child(4) > div .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(1) > .btn:nth-child(1) > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h1:nth-child(2)"));
      assert(elements.size() > 0);
    }
    driver.manage().window().setSize(new Dimension(1296, 696));
  }
  @Test
  public void createandAddnewLabel() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".form-control")).sendKeys("bug6");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".CardDetailContainer_buttonAction__2Sfwo:nth-child(3) > .btn > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector(".btn-light")).click();
    driver.findElement(By.cssSelector("form:nth-child(2) > .form-control")).sendKeys("label");
    driver.findElement(By.cssSelector(".ColorBox_ColorBox__1LZ_B:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector(".OverlayButton_container__3kxDV:nth-child(2) .Label_label__block__3aY7I")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".MuiCollapse-container:nth-child(2) #notistack-snackbar"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void changecardtoprivate() {
    driver.get("https://staging.cicle.app/boards/6110ed43ca295362f6314a7b");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".List_List__30q9z:nth-child(2) .ListContainer_ListContainer__buttonBottom__2kZAI > a")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".form-control")).sendKeys("bug8");
    driver.findElement(By.cssSelector(".btn-success > .Button_container__1WNuB")).click();
    driver.findElement(By.cssSelector("#listcard_content-1 > .OverlayButton_container__3kxDV:nth-child(1) .ModalLinkNoDecor_ModalLink__1zSCj")).click();
    driver.findElement(By.cssSelector(".CardDetailContainer_buttonAction__2Sfwo:nth-child(3) > div .Button_container__1WNuB")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".CardDetailContainer_buttonAction__2Sfwo:nth-child(3) > div .Button_container__1WNuB"));
      assert(elements.size() > 0);
    }
  }
}
