// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GroupChatTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void downloadanattachment() {
    driver.get("https://staging.cicle.app/group-chats/6110ed43ca295324ce314a7d");
    driver.manage().window().setSize(new Dimension(656, 680));
    driver.findElement(By.cssSelector(".CreateGroupMessage_attachmentButton__i4UJs")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Download")).click();
    vars.put("win4914", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4914").toString());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("img"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void sendachat() {
    driver.get("https://staging.cicle.app/group-chats/6110ed43ca295324ce314a7d");
    driver.manage().window().setSize(new Dimension(656, 680));
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ChatButton_container__3Ua3q > .MuiSvgIcon-root")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".Message_Message__3qgbO:nth-child(1) .Message_contentMessage__2NnUS p"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void deleteachat() {
    driver.get("https://staging.cicle.app/group-chats/6110ed43ca295324ce314a7d");
    driver.manage().window().setSize(new Dimension(656, 680));
    {
      WebElement element = driver.findElement(By.cssSelector(".fr-element"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>delete</p>'}", element);
    }
    driver.findElement(By.cssSelector(".ChatButton_container__3Ua3q > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".Message_Message__3qgbO:nth-child(1) .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector("p:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".Button_container__1WNuB")).click();
    assertThat(driver.findElement(By.id("notistack-snackbar")).getText(), is("Delete group chat message success"));
  }
}
